version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - 5432:5432
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    container_name: BKbackend
    volumes:
      - ./postgres:/var/lib/postgresql/data